"""init database migrations

Revision ID: 17ba89426710
Revises:
Create Date: 2024-10-08 15:01:37.943152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '17ba89426710'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('air_quality', 'gpsUpdated',
               existing_type=mysql.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.drop_column('air_quality', 'eco2')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('air_quality', sa.Column('eco2', mysql.DECIMAL(precision=5, scale=2), nullable=True))
    op.alter_column('air_quality', 'gpsUpdated',
               existing_type=sa.Boolean(),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
